name: fzregex
description: "A utility package for validating: Phone, Name, PostalCode, Email, URL, Currency, IP Address, Date, Time, HTMLTags, Password (Strong/Medium), and Credit Card. Designed for Dart/Flutter Developers."
version: 2.1.0
homepage: https://github.com/FrazileDevelopers/FzRegex

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated for Dart 2.17+ and Flutter 3.x compatibility

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0 # Add recommended Dart lints for better code quality

flutter:

  # assets:
  #   - images/

  # fonts:
  #   - family: Google
  #     fonts:
  #       - asset: fonts/google-Regular.ttf
  #       - asset: fonts/google-Italic.ttf
  #         style: italic
